"""empty message

Revision ID: 9b902e807c89
Revises: 6e76ed164cb1
Create Date: 2023-03-31 22:23:36.269830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b902e807c89'
down_revision = '6e76ed164cb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('package', sa.String(length=8), nullable=True))
    op.add_column('user', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('end_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'end_time')
    op.drop_column('user', 'start_time')
    op.drop_column('user', 'package')
    # ### end Alembic commands ###
